typography_spectrum: 0.27628078288398683
color:
  brandStrength: 0.2797124944627285
  lightness: 0.22679419280029833
  saturation: 0.12557281204499304
  rhythmicContrast: 0.991689246846363
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.1091104825027287
author:
  name: Danielle (Dee) Libine
  email: contact@deelee.consulting
  url: 'http://deelee.consulting'
name: vendre sans stress
title: une autre façon de voir le marketing
